name: My First Workflow
on: 
    push:
      branches: 
              - main
    workflow_dispatch:
jobs:
    MyFirstJob:
        runs-on: ubuntu-latest

        steps:
          - run: echo "Hi There World!"
          - name: Checkout
            uses: actions/checkout@v4.2.2
          - name: LIst file in repositoruy
            run: | 
                    echo "The repository ${{ github.repository }} contains the follwoing file:" tree
                            

    
      
