name: Jovica's workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyTestJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi There"
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repo
        run: |
          echo "The repo ${{ github.repository }} contains the following files" tree
